# Generated by Django 6.0.4 on 2026-08-19 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0006_admperm_admrole_admroleperms'),
        ('telecalling', '0036_user_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ManyToManyField(related_name='users', to='adm.admrole'),
        ),
    ]
