# Generated by Django 6.0.4 on 2026-08-19 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telecalling', '0038_alter_user_options_remove_user_role_alter_user_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='perms',
        ),
        migrations.DeleteModel(
            name='Perm',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
