# Generated by Django 6.0.4 on 2026-08-21 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telecalling', '0039_remove_role_perms_delete_perm_delete_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
