# Generated by Django 6.0.4 on 2026-08-21 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0009_collectionquery_pipelinecategory_and_more'),
        ('telecalling', '0040_delete_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignname',
            name='assigned_agents',
            field=models.ManyToManyField(blank=True, related_name='assigned_campaigns', through='adm.CampaignAssignedAgent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaignname',
            name='lead_distribution_type',
            field=models.CharField(blank=True, default='on_demand', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='campaignname',
            name='manager',
            field=models.ForeignKey(blank=True, db_column='manager_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaignname',
            name='pipeline_category',
            field=models.ForeignKey(blank=True, db_column='pipeline_category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='adm.pipelinecategory'),
        ),
        migrations.AlterField(
            model_name='campaignname',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
