# Generated by Django 6.0.4 on 2026-08-21 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecalling', '0041_campaignname_assigned_agents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calldetails',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_stages', to='telecalling.pipelinestage'),
        ),
        migrations.RemoveField(
            model_name='selecttag',
            name='stages',
        ),
        migrations.RemoveField(
            model_name='selecttag',
            name='display_value',
        ),
        migrations.AddField(
            model_name='calldetails',
            name='call_direction',
            field=models.CharField(blank=True, default='Outgoing', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='calldetails',
            name='select_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_priorities', to='telecalling.priority'),
        ),
        migrations.DeleteModel(
            name='Stages',
        ),
    ]
