# Generated by Django 6.0.4 on 2026-09-07 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0014_pipelinecategory_organization_team_organization_and_more'),
        ('telecalling', '0042_alter_calldetails_stage_remove_selecttag_stages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignname',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='adm.organization'),
        ),
        migrations.AddField(
            model_name='lead',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='adm.organization'),
        ),
        migrations.AddField(
            model_name='leadsource',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_sources', to='adm.organization'),
        ),
        migrations.AddField(
            model_name='pipelinestage',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipeline_stages', to='adm.organization'),
        ),
    ]
