# Generated by Django 6.0.4 on 2026-09-16 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0025_rename_adm_perm_perm_gr_e9f969_idx_adm_perm_perm_gr_3422ac_idx_and_more'),
        ('telecalling', '0043_campaignname_organization_lead_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calldetails',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='call_details', to='adm.organization'),
        ),
        migrations.AddField(
            model_name='notification',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='adm.organization'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_settings', to='adm.organization'),
        ),
    ]
