# Generated by Django 6.0.4 on 2026-09-21 10:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telecalling', '0044_calldetails_organization_notification_organization_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Api_Log',
            new_name='ApiLog',
        ),
        migrations.AlterModelTable(
            name='apilog',
            table='api_log',
        ),
    ]
