# Generated by Django 6.0.4 on 2026-09-23 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0027_remove_adminapprovedlosslead_main_reason_and_more'),
        ('telecalling', '0045_rename_api_log_apilog_alter_apilog_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disconnecteddetails',
            name='select_tag',
        ),
        migrations.RemoveField(
            model_name='dropdown',
            name='category',
        ),
        migrations.RemoveField(
            model_name='messagetemplate',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='default_template',
        ),
        migrations.RemoveField(
            model_name='lossleaddetail',
            name='main_reason',
        ),
        migrations.AddField(
            model_name='disconnecteddetails',
            name='select_tag_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lossleaddetail',
            name='main_reason_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='default_template_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='DisconnectStage',
        ),
        migrations.DeleteModel(
            name='Dropdown',
        ),
        migrations.DeleteModel(
            name='DropdownCategory',
        ),
        migrations.DeleteModel(
            name='MessageTemplate',
        ),
        migrations.DeleteModel(
            name='SelectTag',
        ),
        migrations.RunSQL("DROP TABLE IF EXISTS telecalling_authorized_number CASCADE; DROP TABLE IF EXISTS telecalling_user_role CASCADE;"),
    ]
