# Generated by Django 6.0.4 on 2026-09-30 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0028_paymentmode'),
        ('telecalling', '0046_remove_disconnecteddetails_select_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='payment_mode',
            field=models.ForeignKey(blank=True, db_column='payment_mode_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_histories', to='adm.paymentmode'),
        ),
    ]
