# Generated by Django 6.0.4 on 2026-09-30 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0028_paymentmode'),
        ('telecalling', '0047_paymenthistory_payment_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='LossReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loss_reasons', to='adm.organization')),
            ],
            options={
                'db_table': 'telecalling_loss_reason',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='loss_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='telecalling.lossreason'),
        ),
        migrations.AddField(
            model_name='lossleaddetail',
            name='loss_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loss_details', to='telecalling.lossreason'),
        ),
    ]
