# Generated by Django 6.0.4 on 2026-10-05 05:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0029_pipelinestagetranfereddata_and_more'),
        ('telecalling', '0048_lossreason_lead_loss_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinestage',
            name='order_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pipelinestage',
            name='pipeline_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_stages', to='adm.pipelinecategory'),
        ),
        migrations.AddField(
            model_name='pipelinestage',
            name='stage_type',
            field=models.CharField(default='open', max_length=50),
        ),
        migrations.AddField(
            model_name='priority',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='campaignname',
            name='assigned_agents',
            field=models.ManyToManyField(blank=True, related_name='assigned_campaigns', through='adm.campaign_assigned_agent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='priority',
            name='pipeline_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='priorities', to='telecalling.pipelinestage'),
        ),
    ]
