# Generated by Django 6.0.4 on 2026-10-05 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0029_pipelinestagetranfereddata_and_more'),
        ('telecalling', '0049_pipelinestage_order_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lossreason',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loss_reasons', to='adm.pipelinecategory'),
        ),
    ]
