# Generated by Django 6.0.4 on 2026-10-08 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0030_remove_pipelinestagetranfereddata_organization_id_and_more'),
        ('telecalling', '0050_lossreason_pipeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='amountstage',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.organization'),
        ),
        migrations.AddField(
            model_name='amountstage',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.pipelinecategory'),
        ),
        migrations.AddField(
            model_name='apilog',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.organization'),
        ),
        migrations.AddField(
            model_name='apilog',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.pipelinecategory'),
        ),
        migrations.AddField(
            model_name='calldetails',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.pipelinecategory'),
        ),
        migrations.AddField(
            model_name='campaignname',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.pipelinecategory'),
        ),
        migrations.AddField(
            model_name='course',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.organization'),
        ),
        migrations.AddField(
            model_name='course',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.pipelinecategory'),
        ),
        migrations.AddField(
            model_name='coursename',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.organization'),
        ),
        migrations.AddField(
            model_name='coursename',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.pipelinecategory'),
        ),
        migrations.AddField(
            model_name='courseplan',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.organization'),
        ),
        migrations.AddField(
            model_name='courseplan',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.pipelinecategory'),
        ),
        migrations.AddField(
            model_name='coursetiming',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.organization'),
        ),
        migrations.AddField(
            model_name='coursetiming',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.pipelinecategory'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.organization'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.pipelinecategory'),
        ),
        migrations.AddField(
            model_name='deleteddatalog',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.organization'),
        ),
        migrations.AddField(
            model_name='deleteddatalog',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.pipelinecategory'),
        ),
        migrations.AddField(
            model_name='disconnecteddetails',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.organization'),
        ),
        migrations.AddField(
            model_name='disconnecteddetails',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.pipelinecategory'),
        ),
        migrations.AddField(
            model_name='education',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.organization'),
        ),
        migrations.AddField(
            model_name='education',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.pipelinecategory'),
        ),
        migrations.AddField(
            model_name='filterleads',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.organization'),
        ),
        migrations.AddField(
            model_name='filterleads',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.pipelinecategory'),
        ),
        migrations.AddField(
            model_name='filterpayment',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.organization'),
        ),
        migrations.AddField(
            model_name='filterpayment',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.pipelinecategory'),
        ),
        migrations.AddField(
            model_name='filterpipeline',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.organization'),
        ),
        migrations.AddField(
            model_name='filterpipeline',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.pipelinecategory'),
        ),
        migrations.AddField(
            model_name='followup',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.organization'),
        ),
        migrations.AddField(
            model_name='followup',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.pipelinecategory'),
        ),
        migrations.AddField(
            model_name='lead',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.pipelinecategory'),
        ),
        migrations.AddField(
            model_name='leadsource',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.pipelinecategory'),
        ),
        migrations.AddField(
            model_name='lossleaddetail',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.organization'),
        ),
        migrations.AddField(
            model_name='lossleaddetail',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.pipelinecategory'),
        ),
        migrations.AddField(
            model_name='missedfollowuphistory',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.organization'),
        ),
        migrations.AddField(
            model_name='missedfollowuphistory',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.pipelinecategory'),
        ),
        migrations.AddField(
            model_name='notification',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.pipelinecategory'),
        ),
        migrations.AddField(
            model_name='paymentfollowup',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.organization'),
        ),
        migrations.AddField(
            model_name='paymentfollowup',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.pipelinecategory'),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.organization'),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.pipelinecategory'),
        ),
        migrations.AddField(
            model_name='paymentinfo',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.organization'),
        ),
        migrations.AddField(
            model_name='paymentinfo',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.pipelinecategory'),
        ),
        migrations.AddField(
            model_name='paymentstage',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.organization'),
        ),
        migrations.AddField(
            model_name='paymentstage',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.pipelinecategory'),
        ),
        migrations.AddField(
            model_name='paymentstatus',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.organization'),
        ),
        migrations.AddField(
            model_name='paymentstatus',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.pipelinecategory'),
        ),
        migrations.AddField(
            model_name='pipelinestage',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.pipelinecategory'),
        ),
        migrations.AddField(
            model_name='preferredtime',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.organization'),
        ),
        migrations.AddField(
            model_name='preferredtime',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.pipelinecategory'),
        ),
        migrations.AddField(
            model_name='priority',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.organization'),
        ),
        migrations.AddField(
            model_name='priority',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.pipelinecategory'),
        ),
        migrations.AddField(
            model_name='referaldetails',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.organization'),
        ),
        migrations.AddField(
            model_name='referaldetails',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.pipelinecategory'),
        ),
        migrations.AddField(
            model_name='usersecurity',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.organization'),
        ),
        migrations.AddField(
            model_name='usersecurity',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.pipelinecategory'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.pipelinecategory'),
        ),
    ]
