# Generated by Django 6.0.4 on 2026-10-08 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecalling', '0054_delete_collectionquery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='course_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='telecalling.coursename'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='course_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='telecalling.courseplan'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='course_timing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='telecalling.coursetiming'),
        ),
    ]
