# Generated by Django 6.0.4 on 2026-10-08 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecalling', '0056_delete_collectionquery_remove_amountstage_pipeline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseplan',
            name='course_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans', to='telecalling.coursename'),
        ),
        migrations.AddField(
            model_name='courseplan',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='courseplan',
            name='fee_amount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='courseplan',
            name='hours_per_day',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='courseplan',
            name='course_plan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
