# Generated by Django 6.0.4 on 2026-10-08 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecalling', '0057_courseplan_course_name_courseplan_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='trainer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='coursetiming',
            name='course_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timings', to='telecalling.coursename'),
        ),
        migrations.AlterField(
            model_name='course',
            name='batch',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='closing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='starting_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coursetiming',
            name='course_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
