# Generated by Django 6.0.4 on 2026-10-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecalling', '0058_course_trainer_coursetiming_course_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='days',
            field=models.CharField(blank=True, default='Mon–Fri', max_length=50, null=True),
        ),
    ]
