from rest_framework.exceptions import APIException
from adm.models.user import User
from telecalling.models.leads import CampaignName
from adm.models.pipeline_category import PipelineCategory
from adm.models.CampaignAssignedAgent import CampaignAssignedAgent
from adm.services.query_services import exec_raw_sql
from django.db.models import Q


def fetch_pipeline_categories(user, **data):
    try:
        org_id = getattr(user, 'organization_id', None) if user else None
        return exec_raw_sql('L_CATEGORIES', {'organization_id': org_id} if org_id else {})
    except Exception as e:
        raise APIException(str(e))


def fetch_campaign_managers(user, **data):
    try:
        org_id = getattr(user, 'organization_id', None) if user else None
        return exec_raw_sql('L_CAMPAIGN_MANAGERS', {'organization_id': org_id} if org_id else {})
    except Exception as e:
        raise APIException(str(e))


def fetch_campaign_agents(user, **data):
    try:
        org_id = getattr(user, 'organization_id', None) if user else None
        return exec_raw_sql('L_TELECALLERS', {'organization_id': org_id} if org_id else {})
    except Exception as e:
        raise APIException(str(e))


def create_campaign(user, **data):
    try:
        name = data.get("name")
        if not name:
            raise APIException("Campaign Name is required")

        campaign = CampaignName.objects.create(
            name=name,
            pipeline_category_id=data.get("pipeline_category_id"),
            manager_id=data.get("manager_id"),
            lead_distribution_type=data.get("distribution_type", "on_demand"),
            created_by=getattr(user, "username", "admin"),
            organization=getattr(user, 'organization', None)
        )

        agent_objs = [
            CampaignAssignedAgent(campaign=campaign, agent_user_id=agent_id)
            for agent_id in data.get("agent_ids", []) if agent_id
        ]
        if agent_objs:
            CampaignAssignedAgent.objects.bulk_create(agent_objs)

        return {
            "status": True,
            "message": "Campaign Created Successfully",
            "data": {"campaign_id": campaign.id, "campaign_name": campaign.name}
        }
    except Exception as e:
        raise APIException(str(e))


def toggle_campaign_status(user, **data):
    try:
        campaign = CampaignName.objects.filter(id=data.get("campaign_id")).first()
        if not campaign:
            raise APIException("Campaign Not Found")

        campaign.is_active = data.get("is_active", True)
        campaign.save()

        status_text = "Resumed" if campaign.is_active else "Paused"
        return {
            "status": True,
            "message": f"Campaign '{campaign.name}' {status_text} Successfully",
            "data": {"campaign_id": campaign.id, "is_active": campaign.is_active}
        }
    except Exception as e:
        raise APIException(str(e))


def fetch_campaign_detail(user, **data):
    try:
        org_id = getattr(user, 'organization_id', None) if user else None
        c_id = data.get("campaign_id") or 0
        c_name = str(data.get("campaign_name") or "").strip()

        # 1. Fetch Campaign Main Info via SQL Collection Query
        campaign_info = exec_raw_sql('D_FETCH_CAMPAIGN_DETAIL', {
            'organization_id': org_id,
            'campaign_id': c_id,
            'campaign_name': c_name
        })

        if not campaign_info:
            raise APIException("Campaign Not Found")

        detail = campaign_info[0]

        # 2. Fetch Agents List via SQL Collection Query (s_no generated by ROW_NUMBER() in SQL - 0 Python Loops!)
        detail['agents'] = exec_raw_sql('D_FETCH_CAMPAIGN_AGENTS', {
            'organization_id': org_id,
            'campaign_id': detail['campaign_id']
        }) or []

        return {
            "status": True,
            "message": "Campaign Detail Fetched Successfully",
            "data": detail
        }
    except Exception as e:
        raise APIException(str(e))


def update_campaign_detail(user, **data):
    try:
        c_id = data.get("campaign_id")
        c_name = data.get("campaign_name")
        campaign = CampaignName.objects.filter(id=c_id).first() if c_id else CampaignName.objects.filter(name__iexact=str(c_name).strip()).first()

        if not campaign:
            raise APIException("Campaign Not Found")

        if data.get("is_active") is not None:
            campaign.is_active = data["is_active"]
        if data.get("lead_distribution_type"):
            campaign.lead_distribution_type = data["lead_distribution_type"]
        campaign.save()

        for item in data.get("agent_toggles", []):
            if item.get("agent_id") is not None and item.get("is_active") is not None:
                ca, _ = CampaignAssignedAgent.objects.get_or_create(campaign=campaign, agent_user_id=item["agent_id"])
                ca.is_active = item["is_active"]
                ca.save()

        return {"status": True, "message": "Campaign Details Updated Successfully"}
    except Exception as e:
        raise APIException(str(e))