from rest_framework.exceptions import APIException
from adm.models.user import User
from telecalling.models.leads import CampaignName
from adm.models.pipeline_category import PipelineCategory
from adm.models.campaign_assigned_agent import campaign_assigned_agent
from adm.services.query_services import exec_raw_sql
from django.db.models import Q


def fetch_pipeline_categories(user, **data):
    try:
        org_id = getattr(user, 'organization_id', None) if user else None
        return exec_raw_sql('L_CATEGORIES', {'organization_id': org_id} if org_id else {})
    except Exception as e:
        raise APIException(str(e))


def fetch_campaign_managers(user, **data):
    try:
        org_id = getattr(user, 'organization_id', None) if user else None
        return exec_raw_sql('L_CAMPAIGN_MANAGERS', {'organization_id': org_id} if org_id else {})
    except Exception as e:
        raise APIException(str(e))


def fetch_campaign_agents(user, **data):
    try:
        org_id = getattr(user, 'organization_id', None) if user else None
        return exec_raw_sql('L_TELECALLERS', {'organization_id': org_id} if org_id else {})
    except Exception as e:
        raise APIException(str(e))


def create_campaign(user, **data):
    try:
        name = data.get("name")
        if not name:
            raise APIException("Campaign Name is required")

        campaign = CampaignName.objects.create(
            name=name,
            pipeline_category_id=data.get("pipeline_category_id"),
            manager_id=data.get("manager_id"),
            lead_distribution_type=data.get("distribution_type", "on_demand"),
            created_by=getattr(user, "username", "admin"),
            organization=getattr(user, 'organization', None)
        )

        agent_objs = [
            campaign_assigned_agent(campaign=campaign, agent_user_id=agent_id)
            for agent_id in data.get("agent_ids", []) if agent_id
        ]
        if agent_objs:
            campaign_assigned_agent.objects.bulk_create(agent_objs)

        return {
            "status": True,
            "message": "Campaign Created Successfully",
            "data": {"campaign_id": campaign.id, "campaign_name": campaign.name}
        }
    except Exception as e:
        raise APIException(str(e))


def toggle_campaign_status(user, **data):
    try:
        campaign = CampaignName.objects.filter(id=data.get("campaign_id")).first()
        if not campaign:
            raise APIException("Campaign Not Found")

        campaign.is_active = data.get("is_active", True)
        campaign.save()

        status_text = "Resumed" if campaign.is_active else "Paused"
        return {
            "status": True,
            "message": f"Campaign '{campaign.name}' {status_text} Successfully",
            "data": {"campaign_id": campaign.id, "is_active": campaign.is_active}
        }
    except Exception as e:
        raise APIException(str(e))


def fetch_campaign_detail(user, **data):
    try:
        org_id = getattr(user, 'organization_id', None) if user else None
        c_id = data.get("campaign_id") or 0
        c_name = str(data.get("campaign_name") or "").strip()

        # 1. Fetch Campaign Main Info via SQL Collection Query
        campaign_info = exec_raw_sql('D_FETCH_CAMPAIGN_DETAIL', {
            'organization_id': org_id,
            'campaign_id': c_id,
            'campaign_name': c_name
        })

        if not campaign_info:
            raise APIException("Campaign Not Found")

        detail = campaign_info[0]

        # 2. Fetch Agents List via SQL Collection Query (s_no generated by ROW_NUMBER() in SQL - 0 Python Loops!)
        detail['agents'] = exec_raw_sql('D_FETCH_CAMPAIGN_AGENTS', {
            'organization_id': org_id,
            'campaign_id': detail['campaign_id']
        }) or []

        return {
            "status": True,
            "message": "Campaign Detail Fetched Successfully",
            "data": detail
        }
    except Exception as e:
        raise APIException(str(e))


def update_campaign_detail(user, **data):
    try:
        c_id = data.get("campaign_id")
        c_name = data.get("campaign_name")
        campaign = CampaignName.objects.filter(id=c_id).first() if c_id else CampaignName.objects.filter(name__iexact=str(c_name).strip()).first()

        if not campaign:
            raise APIException("Campaign Not Found")

        if data.get("is_active") is not None:
            campaign.is_active = data["is_active"]
        if data.get("lead_distribution_type"):
            campaign.lead_distribution_type = data["lead_distribution_type"]
        campaign.save()

        for item in data.get("agent_toggles", []):
            if item.get("agent_id") is not None and item.get("is_active") is not None:
                ca, _ = campaign_assigned_agent.objects.get_or_create(campaign=campaign, agent_user_id=item["agent_id"])
                ca.is_active = item["is_active"]
                ca.save()

        return {"status": True, "message": "Campaign Details Updated Successfully"}
    except Exception as e:
        raise APIException(str(e))


def auto_assign_campaign_leads(campaign_id, lead_ids=None, distribution_mode=None):
    from telecalling.models.leads import Lead

    try:
        if not campaign_id:
            return {"status": False, "assigned_count": 0, "message": "Campaign ID is required"}

        campaign = CampaignName.objects.filter(id=campaign_id).first()
        if not campaign or not campaign.is_active:
            return {"status": False, "assigned_count": 0, "message": "Campaign not found or inactive"}

        # 1. Mode Selection (Round-Robin vs On-Demand)
        mode = (distribution_mode or campaign.lead_distribution_type or "round_robin").lower().strip()

        # 2. ON-DEMAND MODE (Leads stay unassigned in Campaign Pool)
        if mode in ["on_demand", "ondemand", "pool"]:
            return {
                "status": True,
                "assigned_count": 0,
                "mode": "on_demand",
                "message": "Leads placed in On-Demand Campaign Pool (assigned_to = NULL)"
            }

        # 3. ROUND-ROBIN MODE: Fetch Active Telecaller IDs via Collection Query (0.0001 sec!)
        agent_rows = exec_raw_sql('L_CAMPAIGN_ELIGIBLE_AGENTS', {'campaign_id': campaign_id}) or []
        agent_ids = [r['id'] for r in agent_rows if r.get('id')]

        if not agent_ids:
            return {"status": False, "assigned_count": 0, "message": "No active eligible telecallers found for this campaign"}

        # 4. Fetch Unassigned Leads
        if lead_ids:
            leads_qs = Lead.objects.filter(id__in=lead_ids, campaign=campaign, assigned_to__isnull=True)
        else:
            leads_qs = Lead.objects.filter(campaign=campaign, assigned_to__isnull=True)

        leads = list(leads_qs.order_by('id'))
        if not leads:
            return {"status": True, "assigned_count": 0, "message": "No unassigned leads found to distribute"}

        # 5. Super-Fast Memory Slice Allocation (NO loop save() delays!)
        num_agents = len(agent_ids)
        for idx, agent_id in enumerate(agent_ids):
            agent_leads = leads[idx::num_agents]
            for l in agent_leads:
                l.assigned_to_id = agent_id

        # 6. Bulk Update in 1 Single SQL Query (0.05 seconds for 10,000 Leads!)
        Lead.objects.bulk_update(leads, ['assigned_to'], batch_size=1000)

        return {
            "status": True,
            "assigned_count": len(leads),
            "agents_count": num_agents,
            "mode": "round_robin",
            "message": f"Successfully auto-assigned {len(leads)} leads across {num_agents} active telecallers!"
        }

    except Exception as e:
        raise APIException(str(e))