# Generated by Django 6.0.4 on 2026-08-19 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0005_team_usertarget'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmPerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_value', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('perm_group', models.CharField(default='perm_apis', max_length=50)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'db_table': 'adm_perm',
                'indexes': [models.Index(fields=['code'], name='adm_perm_code_d6aef1_idx'), models.Index(fields=['name'], name='adm_perm_name_5b5334_idx'), models.Index(fields=['perm_group'], name='adm_perm_perm_gr_e9f969_idx')],
            },
        ),
        migrations.CreateModel(
            name='AdmRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_value', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'adm_role',
                'indexes': [models.Index(fields=['name'], name='adm_role_name_beb623_idx'), models.Index(fields=['code'], name='adm_role_code_5f20c5_idx')],
            },
        ),
        migrations.CreateModel(
            name='AdmRolePerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_roles', to='adm.admperm')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='adm.admrole')),
            ],
            options={
                'verbose_name': 'Role Permission',
                'verbose_name_plural': 'Role Permissions',
                'db_table': 'adm_role_perms',
                'indexes': [models.Index(fields=['role', 'perm'], name='adm_role_pe_role_id_81d4ad_idx')],
                'unique_together': {('role', 'perm')},
            },
        ),
    ]
