# Generated by Django 6.0.4 on 2026-08-19 09:49

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0006_admperm_admrole_admroleperms'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_value', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('perm_group', models.CharField(default='perm_apis', max_length=50)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'db_table': 'adm_perm',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_value', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'adm_role',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(db_index=True, max_length=255, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('user_profile', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile', models.CharField(blank=True, max_length=25, null=True)),
                ('user_type', models.CharField(blank=True, max_length=25, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('wrong_pwd_counts', models.IntegerField(default=0)),
                ('starting_date', models.DateField(default=datetime.date.today)),
                ('ending_date', models.DateField(blank=True, null=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('last_pwd_changed_at', models.DateTimeField(blank=True, null=True)),
                ('validate_token', models.CharField(blank=True, max_length=20, null=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('deact_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('joining_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Admin User',
                'verbose_name_plural': 'Admin Users',
                'db_table': 'adm_user',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'User Role',
                'verbose_name_plural': 'User Roles',
                'db_table': 'adm_user_role',
            },
        ),
        migrations.RemoveIndex(
            model_name='admperm',
            name='adm_perm_code_d6aef1_idx',
        ),
        migrations.RemoveIndex(
            model_name='admperm',
            name='adm_perm_name_5b5334_idx',
        ),
        migrations.RemoveIndex(
            model_name='admperm',
            name='adm_perm_perm_gr_e9f969_idx',
        ),
        migrations.RemoveIndex(
            model_name='admrole',
            name='adm_role_name_beb623_idx',
        ),
        migrations.RemoveIndex(
            model_name='admrole',
            name='adm_role_code_5f20c5_idx',
        ),
        migrations.AlterUniqueTogether(
            name='admroleperms',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='admroleperms',
            name='adm_role_pe_role_id_81d4ad_idx',
        ),
        migrations.AddIndex(
            model_name='perm',
            index=models.Index(fields=['code'], name='adm_perm_code_d6aef1_idx'),
        ),
        migrations.AddIndex(
            model_name='perm',
            index=models.Index(fields=['name'], name='adm_perm_name_5b5334_idx'),
        ),
        migrations.AddIndex(
            model_name='perm',
            index=models.Index(fields=['perm_group'], name='adm_perm_perm_gr_e9f969_idx'),
        ),
        migrations.AddField(
            model_name='role',
            name='perms',
            field=models.ManyToManyField(db_table='adm_role_perms', related_name='roles', to='adm.perm'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='adm_user_groups', related_query_name='adm_user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adm_users', to='adm.role'),
        ),
        migrations.AddField(
            model_name='user',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adm_members', to='adm.team'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='adm_user_permissions', related_query_name='adm_user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_users', to='adm.role'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='adm.user'),
        ),
        migrations.RemoveField(
            model_name='admroleperms',
            name='perm',
        ),
        migrations.RemoveField(
            model_name='admroleperms',
            name='role',
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['name'], name='adm_role_name_beb623_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['code'], name='adm_role_code_5f20c5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('user', 'role')},
        ),
        migrations.DeleteModel(
            name='AdmPerm',
        ),
    ]
