# Generated by Django 6.0.4 on 2026-08-19 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0007_perm_role_user_userrole_and_more'),
        ('telecalling', '0038_alter_user_options_remove_user_role_alter_user_table_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdmRole',
        ),
        migrations.DeleteModel(
            name='AdmRolePerms',
        ),
    ]
