# Generated by Django 6.0.4 on 2026-08-21 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0009_collectionquery_pipelinecategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
    ]
