# Generated by Django 6.0.4 on 2026-08-24 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0011_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
