# Generated by Django 6.0.4 on 2026-09-07 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0012_remove_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(blank=True, null=True, upload_to='org_logos/')),
                ('organization_name', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('industry_type', models.CharField(blank=True, max_length=100, null=True)),
                ('company_website', models.URLField(blank=True, max_length=255, null=True)),
                ('company_description', models.TextField(blank=True, null=True)),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('pincode', models.CharField(max_length=20)),
                ('official_email', models.EmailField(max_length=255)),
                ('official_contact', models.CharField(max_length=25)),
                ('gstin', models.CharField(blank=True, max_length=50, null=True)),
                ('company_pan', models.CharField(blank=True, max_length=50, null=True)),
                ('date_format', models.CharField(default='DD/MM/YYYY', max_length=20)),
                ('time_format', models.CharField(default='24hrs', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'db_table': 'adm_organization',
            },
        ),
    ]
