# Generated by Django 6.0.4 on 2026-09-07 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0014_pipelinecategory_organization_team_organization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='region',
        ),
    ]
