# Generated by Django 6.0.4 on 2026-09-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0015_remove_team_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='time_format',
            field=models.CharField(default='12hrs (AM/PM)', max_length=20),
        ),
    ]
