# Generated by Django 6.0.4 on 2026-09-07 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0016_alter_organization_time_format'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usertarget',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='usertarget',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_targets', to='adm.team'),
        ),
        migrations.AlterField(
            model_name='usertarget',
            name='telecaller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performance_targets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='usertarget',
            name='target_calls',
        ),
    ]
