# Generated by Django 6.0.4 on 2026-09-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0017_alter_usertarget_unique_together_usertarget_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertarget',
            name='target_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='org_logos/'),
        ),
    ]
