# Generated by Django 6.0.4 on 2026-09-11 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0018_usertarget_target_amount_alter_organization_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertarget',
            name='target_calls',
            field=models.IntegerField(default=800),
        ),
    ]
