# Generated by Django 6.0.4 on 2026-09-11 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0019_usertarget_target_calls'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_month', models.DateField()),
                ('target_admissions', models.IntegerField(default=0)),
                ('target_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('target_calls', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_individual_targets', to='adm.team')),
                ('telecaller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_monthly_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'adm_individual_target',
            },
        ),
        migrations.CreateModel(
            name='TeamTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_month', models.DateField()),
                ('target_admissions', models.IntegerField(default=0)),
                ('target_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('target_calls', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_monthly_targets', to='adm.team')),
            ],
            options={
                'db_table': 'adm_team_target',
            },
        ),
        migrations.DeleteModel(
            name='UserTarget',
        ),
    ]
