# Generated by Django 6.0.4 on 2026-09-16 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0020_individualtarget_teamtarget_delete_usertarget'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('display_value', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'adm_perm_group',
            },
        ),
        migrations.RemoveField(
            model_name='perm',
            name='perm_group',
        ),
        migrations.AddField(
            model_name='perm',
            name='perm_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permissions', to='adm.permgroup'),
        ),
    ]
