# Generated by Django 6.0.4 on 2026-09-16 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0021_permgroup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='data_scope',
            field=models.CharField(blank=True, default='own', max_length=20, null=True),
        ),
    ]
