# Generated by Django 6.0.4 on 2026-09-16 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0022_rename_adm_perm_perm_gr_e9f969_idx_adm_perm_perm_gr_3422ac_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='data_scope',
        ),
    ]
