# Generated by Django 6.0.4 on 2026-09-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0023_rename_adm_perm_perm_gr_e9f969_idx_adm_perm_perm_gr_3422ac_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
