# Generated by Django 6.0.4 on 2026-09-17 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0025_rename_adm_perm_perm_gr_e9f969_idx_adm_perm_perm_gr_3422ac_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='perm',
            new_name='adm_perm_perm_gr_3422ac_idx',
            old_name='adm_perm_perm_gr_e9f969_idx',
        ),
    ]
