# Generated by Django 6.0.4 on 2026-09-23 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0026_rename_adm_perm_perm_gr_e9f969_idx_adm_perm_perm_gr_3422ac_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminapprovedlosslead',
            name='main_reason',
        ),
        migrations.AddField(
            model_name='adminapprovedlosslead',
            name='main_reason_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
