# Generated by Django 6.0.4 on 2026-10-05 05:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0028_paymentmode'),
        ('telecalling', '0048_lossreason_lead_loss_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineStageTranferedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_stage_id', models.IntegerField()),
                ('pipeline_id', models.IntegerField(blank=True, null=True)),
                ('pipeline_name', models.CharField(blank=True, max_length=150, null=True)),
                ('stage_name', models.CharField(max_length=150)),
                ('stage_type', models.CharField(default='open', max_length=50)),
                ('order_no', models.IntegerField(default=1)),
                ('organization_id', models.IntegerField(blank=True, null=True)),
                ('organization_name', models.CharField(blank=True, max_length=150, null=True)),
                ('tags_snapshot', models.JSONField(blank=True, default=list)),
                ('leads_transferred_count', models.IntegerField(default=0)),
                ('transferred_lead_ids', models.JSONField(blank=True, default=list)),
                ('transferred_leads_snapshot', models.JSONField(blank=True, default=list)),
                ('calls_snapshot', models.JSONField(blank=True, default=list)),
                ('pending_followups_snapshot', models.JSONField(blank=True, default=list)),
                ('payments_snapshot', models.JSONField(blank=True, default=dict)),
                ('target_stage_id', models.IntegerField(blank=True, null=True)),
                ('target_stage_name', models.CharField(blank=True, max_length=150, null=True)),
                ('target_tag_id', models.IntegerField(blank=True, null=True)),
                ('target_tag_name', models.CharField(blank=True, max_length=150, null=True)),
                ('deletion_reason', models.TextField(blank=True, null=True)),
                ('deleted_by', models.CharField(default='admin', max_length=150)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'adm_pipeline_stage_tranfered_data',
                'ordering': ['-deleted_at'],
            },
        ),
        migrations.AddField(
            model_name='pipelinecategory',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='campaign_assigned_agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_leads_count', models.IntegerField(blank=True, default=None, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('agent_user', models.ForeignKey(db_column='agent_user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(db_column='campaign_id', on_delete=django.db.models.deletion.CASCADE, to='telecalling.campaignname')),
            ],
            options={
                'db_table': 'adm_campaign_assigned_agents',
                'unique_together': {('campaign', 'agent_user')},
            },
        ),
        migrations.DeleteModel(
            name='CampaignAssignedAgent',
        ),
    ]
