# Generated by Django 6.0.4 on 2026-10-08 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0029_pipelinestagetranfereddata_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipelinestagetranfereddata',
            name='organization_id',
        ),
        migrations.RemoveField(
            model_name='pipelinestagetranfereddata',
            name='pipeline_id',
        ),
        migrations.AddField(
            model_name='adminapprovedlosslead',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.organization'),
        ),
        migrations.AddField(
            model_name='adminapprovedlosslead',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.pipelinecategory'),
        ),
        migrations.AddField(
            model_name='adminleadreassignhistory',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.organization'),
        ),
        migrations.AddField(
            model_name='adminleadreassignhistory',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.pipelinecategory'),
        ),
        migrations.AddField(
            model_name='adminlossactionlog',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.organization'),
        ),
        migrations.AddField(
            model_name='adminlossactionlog',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.pipelinecategory'),
        ),
        migrations.AddField(
            model_name='campaign_assigned_agent',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.organization'),
        ),
        migrations.AddField(
            model_name='campaign_assigned_agent',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.pipelinecategory'),
        ),
        migrations.AddField(
            model_name='collectionquery',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.organization'),
        ),
        migrations.AddField(
            model_name='collectionquery',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.pipelinecategory'),
        ),
        migrations.AddField(
            model_name='individualtarget',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.pipelinecategory'),
        ),
        migrations.AddField(
            model_name='paymentmode',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.pipelinecategory'),
        ),
        migrations.AddField(
            model_name='perm',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.organization'),
        ),
        migrations.AddField(
            model_name='perm',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.pipelinecategory'),
        ),
        migrations.AddField(
            model_name='permgroup',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.organization'),
        ),
        migrations.AddField(
            model_name='permgroup',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.pipelinecategory'),
        ),
        migrations.AddField(
            model_name='pipelinecategory',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.pipelinecategory'),
        ),
        migrations.AddField(
            model_name='pipelinestagetranfereddata',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.organization'),
        ),
        migrations.AddField(
            model_name='pipelinestagetranfereddata',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.pipelinecategory'),
        ),
        migrations.AddField(
            model_name='role',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.organization'),
        ),
        migrations.AddField(
            model_name='role',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.pipelinecategory'),
        ),
        migrations.AddField(
            model_name='team',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.pipelinecategory'),
        ),
        migrations.AddField(
            model_name='teamtarget',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.pipelinecategory'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_all_pipelines_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.pipelinecategory'),
        ),
        migrations.AddField(
            model_name='user',
            name='pipeline_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userrole',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.organization'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.pipelinecategory'),
        ),
    ]
