# Generated by Django 6.0.4 on 2026-10-08 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0030_remove_pipelinestagetranfereddata_organization_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='adm.pipelinecategory'),
        ),
    ]
