# Generated by Django 6.0.4 on 2026-10-08 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0031_alter_team_pipeline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionquery',
            name='pipeline',
        ),
        migrations.RemoveField(
            model_name='individualtarget',
            name='pipeline',
        ),
        migrations.RemoveField(
            model_name='paymentmode',
            name='pipeline',
        ),
        migrations.RemoveField(
            model_name='pipelinecategory',
            name='pipeline',
        ),
        migrations.RemoveField(
            model_name='role',
            name='pipeline',
        ),
        migrations.RemoveField(
            model_name='teamtarget',
            name='pipeline',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='pipeline',
        ),
    ]
