# Generated by Django 6.0.4 on 2026-10-08 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0032_remove_collectionquery_pipeline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pipeline',
        ),
    ]
